name: Publish package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    uses: cabify/javascript-actions/.github/workflows/npm_publish.yml@main
    with:
      tag: ${{ contains(github.ref_name,'beta') && 'beta' || 'latest' }}
    secrets:
      token: ${{ secrets.NPM_TOKEN }}
